version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10.0.0

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies

      - run: yarn install

      - run: yarn test

      - save_cache:
          paths:
            - ~/.cache
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - app

  semantic_release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies

      - run: yarn semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build

      - semantic_release:
          context: semantic-release
          requires:
            - build
