version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10.0.0

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run: yarn install

      - run: yarn test

      - persist_to_workspace:
          root: ~/
          paths:
            - app

  semantic_release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run: yarn semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build

      - semantic_release:
          context: semantic-release
          requires:
            - build
