version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.0.0

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  semantic_release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: build

      - semantic_release:
          context: semantic-release
          requires:
            - build
